version: '3.4'

services:
  webapi:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductDb;User=sa;Password=YourStrongPassword;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrongPassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
